source "https://rubygems.org"

group :development do
	# These gems were loaded from the standard library by Fastlane,
	# but will no longer be part of the default gems since Ruby 3.4.0.
	# Includes them directly until Fastlane fixes it.
	gem "abbrev"
	gem "ostruct"

	gem "fastlane", "~> 2.225"
end

plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
