name: Update Config
description: 'Updates the configuration'

runs:
  using: composite
  steps:
    - name: Update Configuration (loginRequestURL)
      shell: bash
      run: |
        file="assets/config_authentication_cloud.json"
        jq '.login.loginRequestURL = "https://${{ env.HOST_NAME }}.mauth.nevis.cloud/_app/auth/pwd"' "$file" > /tmp/jq_out.json && mv /tmp/jq_out.json "$file"

    - name: Update Configuration (hostname)
      shell: bash
      run: |
        file="assets/config_authentication_cloud.json"
        jq '.sdk.hostname = "${{ env.HOST_NAME }}.mauth.nevis.cloud"' "$file" > /tmp/jq_out.json && mv /tmp/jq_out.json "$file"
