source "https://cdn.cocoapods.org"

deployment_target = "15.5"
platform :ios, deployment_target

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV["COCOAPODS_DISABLE_STATS"] = "true"

project "Runner", {
	"Debug" => :debug,
	"Profile" => :debug,
	"Release" => :release,
}

def flutter_root
	generated_xcode_build_settings_path = File.expand_path(File.join("..", "Flutter", "Generated.xcconfig"), __FILE__)
	unless File.exist?(generated_xcode_build_settings_path)
		raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
	end

	File.foreach(generated_xcode_build_settings_path) do |line|
		matches = line.match(/FLUTTER_ROOT=(.*)/)
		return matches[1].strip if matches
	end
	raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join("packages", "flutter_tools", "bin", "podhelper"), flutter_root)

flutter_ios_podfile_setup

target "Runner" do
	use_frameworks!
	use_modular_headers!

	pod "NevisMobileAuthentication-Debug", "~> 4.2.0", configurations: ["Debug", "Profile"]
	pod "NevisMobileAuthentication", "~> 4.2.0", configurations: ["Release"]

	flutter_install_all_ios_pods __dir__
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		flutter_additional_ios_build_settings(target)
		target.build_configurations.each do |config|
			config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] ||= ["$(inherited)", "PERMISSION_CAMERA=1"]
			config.build_settings["ENABLE_BITCODE"] = "NO" # NMA SDK does not support Bitcode
			config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = deployment_target
		end
	end
end
