name: Setup iOS Environment
description: Sets up the environment for iOS

runs:
  using: composite
  steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ env.XCODE_VERSION }}

    - name: Cache RubyGem Dependencies
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
        bundler-cache: true
        working-directory: 'ios'

    - name: Setup .netrc for github.com
      if: ${{ env.BUILD_TYPE == 'SNAPSHOT' }}
      uses: extractions/netrc@v3
      with:
        machine: github.com
        username: ${{ env.GH_USERNAME }}
        password: ${{ env.GH_PERSONAL_ACCESS_TOKEN }}

    - name: Setup .netrc for api.github.com
      if: ${{ env.BUILD_TYPE == 'SNAPSHOT' }}
      uses: extractions/netrc@v3
      with:
        machine: api.github.com
        username: ${{ env.GH_USERNAME }}
        password: ${{ env.GH_PERSONAL_ACCESS_TOKEN }}
