name: Setup Flutter
description: Sets up Flutter

runs:
  using: composite
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true
        cache-key: ${{ runner.os }}-flutter-cache-${{ env.FLUTTER_VERSION }}

