name: Lint Flutter
description: Lints Flutter code by formatting and analyzing

runs:
  using: composite
  steps:
    - name: Run Dart Format
      shell: bash
      run: dart format --set-exit-if-changed .

    - name: Run Flutter Analyzer
      shell: bash
      run: flutter analyze
