name: Pull Request

on:
  pull_request:
    branches: [ 'develop' ]
  workflow_dispatch:
    inputs:
      ios-runner-type:
        type: choice
        required: true
        description: "Runner type"
        default: "self-hosted"
        options:
          - "self-hosted"
          - "macos-13"

env:
  BUILD_TYPE: 'SNAPSHOT' # Allowed values: 'SNAPSHOT', 'RELEASE', 'RELEASE_CANDIDATE'
  FLUTTER_VERSION: '3.19.0'
  XCODE_VERSION: '15.4'
  JAVA_VERSION: '17'
  RUBY_VERSION: '3.1'
  HOST_NAME: ${{ secrets.HOST_NAME }}
  PRIVATE_REPOSITORY_API_KEY: ${{ secrets.PRIVATE_REPOSITORY_API_KEY }}
  PRIVATE_DART_REPOSITORY: ${{ secrets.PRIVATE_DART_REPOSITORY }}
  PRIVATE_NATIVE_IOS_REPOSITORY: ${{ secrets.PRIVATE_NATIVE_IOS_REPOSITORY }}
  PRIVATE_NATIVE_ANDROID_REPOSITORY: ${{ secrets.PRIVATE_NATIVE_ANDROID_REPOSITORY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
  GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  CURRENT_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  flutter-validation:
    name: Validate Flutter
    runs-on: ubuntu-latest
    outputs:
      sdk-version: ${{ steps.get-versions.outputs.sdk-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch SDK Version
        id: get-versions
        uses: ./.github/actions/get-versions

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Update Flutter dependencies
        uses: ./.github/actions/update-flutter-dependencies
        with:
          sdk-version: ${{ steps.get-versions.outputs.sdk-version }}

      - name: Validate Flutter
        uses: ./.github/actions/validate-flutter

  ios-build:
    name: Building iOS App
    runs-on: ${{ github.event.inputs.ios-runner-type || 'self-hosted' }}
    needs: [flutter-validation]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Update Flutter Dependencies
        uses: ./.github/actions/update-flutter-dependencies
        with:
          sdk-version: ${{ needs.flutter-validation.outputs.sdk-version }}

      - name: Setup iOS Environment
        uses: ./.github/actions/setup-ios

      - name: Build iOS Example App
        env:
          PRIVATE_NATIVE_REPOSITORY: ${{ env.PRIVATE_NATIVE_IOS_REPOSITORY }}
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'pr'
          subdirectory: 'ios'

  android-build:
    name: Building Android App
    runs-on: ubuntu-latest
    needs: [flutter-validation]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Update Flutter Dependencies
        uses: ./.github/actions/update-flutter-dependencies
        with:
          sdk-version: ${{ needs.flutter-validation.outputs.sdk-version }}

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Build Android Example App
        env:
          PRIVATE_NATIVE_REPOSITORY: ${{ env.PRIVATE_NATIVE_ANDROID_REPOSITORY }}
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'pr'
          subdirectory: 'android'
