# A reusable workflow file for publishing a Flutter package

name: Publish Flutter Package

on:
  workflow_call:
    inputs:
      version:
        description: "The current version number"
        required: true
        type: string
      build-number:
        description: "The current build number"
        required: true
        type: string
    secrets:
      HOST_NAME:
        required: true
      KEYSTORE_FILE:
        required: true
      SIGNING_CONFIGS:
        required: true
      GITHUB_USERNAME:
        required: true
      GITHUB_PERSONAL_ACCESS_TOKEN:
        required: true
      FIREBASE_TOKEN:
        required: true
      FIREBASE_APP_ID_ANDROID:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

env:
  FLUTTER_VERSION: '3.0.1'
  JAVA_VERSION: '11'
  RUBY_VERSION: '3.0'
  CURRENT_BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE
      - name: Checkout Project
        uses: actions/checkout@v3

      # Update the Auth Cloud configuration
      - name: Update Configuration
        uses: './.github/actions/update-config'
        with:
          host-name: ${{ secrets.HOST_NAME }}

        # Make sure the stable version of Flutter is available
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: ${{ runner.os }}-flutter-cache-${{ env.FLUTTER_VERSION }}

      # Set Ruby version and Cache RubyGem dependencies
      - name: Cache RubyGem Dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: 'android'

      # Increment build number in the pubspec.yaml file
      - name: Increment Build Number
        run: |
          dart pub global activate cider
          cider bump build --build=${{ inputs.build-number }}

      # Resolve Flutter packages
      - name: Resolve Flutter packages
        run: flutter pub get

      # Ensure correct Java version is installed
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      # Move the Java keystore to its place
      - name: Decode Keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore-example-app.jks'
          fileDir: './android/etc'
          encodedString: ${{ secrets.KEYSTORE_FILE }}

      # Distribute the Android app
      - name: Run Fastlane
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SIGNING_CONFIGS: ${{ secrets.SIGNING_CONFIGS }}
          GITHUB_USERNAME: ${{ secrets.SIGNING_CONFIGS }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: maierj/fastlane-action@v3.0.0
        with:
          lane: 'main'
          subdirectory: 'android'
          options: '{ "version": "${{ inputs.version }}",
                      "build_number": "${{ inputs.build-number }}"
                    }'